theme: jekyll-theme-cayman
title: Curso completo de estadística inferencial con R y Python
description: Estadística Inferencial para Machine Learning e Inteligencia Artificial con R y Python con los Drs R.Alberich y A.Mir
url: https://www.udemy.com/course/probabilidad-y-variables-aleatorias-para-ml-con-r-y-python/?couponCode=B85F8D52148DF5AAD8F7